import { useUser } from "@clerk/nextjs";
import { type NextPage } from "next"; 
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { api } from "~/utils/api";

const ListingView: NextPage = () => {
  const router = useRouter();
  const user = useUser();

const listing = api.listing.get.useQuery({
  listingId :router.query.id as string,
},{
  enabled:!! router.query.id,
});

const listingItem = listing.data;

if(!listingItem){
  return;
}
  
  return (
    <>
      <Head>
        <title>View Listing</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col gap-12 bg-gray-800">
        <div className="container mx-auto flex flex-col gap-12">
          <h1 className="mt-12 text-4xl">{listingItem.name}</h1>
          <p className="mt-12 text-4xl">{listingItem.description}</p>
          <h1 className="mt-12 text-4xl">{listingItem.price}</h1>
        </div>
        {user.isSignedIn && (
        <>
        <button
            className="bg-blue-500 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded-full mt-4" >
              <Link href={`/orderitem/${listingItem.id}`}>Order Now</Link>
           </button>
        </>
        )}
      </main>
    </>
  );
};

export default ListingView;